version: '3'
volumes:
  CRMDbData:
services:
  database:
    image: 'postgres:13-alpine'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: usr_crm
      POSTGRES_PASSWORD: 123456
      PGPASSWORD: 123456
      POSTGRES_DB: crm_database
      PGDATA: /db_data
    volumes:
      - CRMDbData:/db_data