# Generated by Django 3.2.5 on 2021-07-24 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import organizations.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_auto_20210724_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('organization_phone', models.CharField(max_length=15)),
                ('number_of_workers', models.PositiveIntegerField()),
                ('owner_of_organization', models.CharField(max_length=30)),
                ('owner_phone', models.CharField(max_length=15, validators=[organizations.validators.PhoneValidator()])),
                ('owner_email', models.EmailField(max_length=254)),
                ('submit_date', models.DateField(auto_now_add=True)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.organizationproduct')),
                ('submit_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
