# Generated by Django 3.2.5 on 2021-07-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210724_1823'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='products',
        ),
        migrations.AddField(
            model_name='organization',
            name='products',
            field=models.ManyToManyField(to='products.OrganizationProduct'),
        ),
    ]
