# Generated by Django 3.2.5 on 2021-08-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210728_1836'),
        ('sale', '0004_alter_quoteitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoteitem',
            name='product',
        ),
        migrations.AddField(
            model_name='quoteitem',
            name='products',
            field=models.ManyToManyField(to='products.Product'),
        ),
    ]
