# Generated by Django 3.2.5 on 2021-08-01 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210728_1836'),
        ('sale', '0005_auto_20210801_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoteitem',
            name='products',
        ),
        migrations.AddField(
            model_name='quoteitem',
            name='discount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='quoteitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
