# Generated by Django 3.2.5 on 2021-08-06 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20210724_1927'),
        ('sale', '0010_followup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailhistory',
            options={'verbose_name': 'Email History', 'verbose_name_plural': 'Email Histories'},
        ),
        migrations.AddField(
            model_name='followup',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organizations.organization'),
        ),
    ]
