# Generated by Django 3.2.5 on 2021-07-24 13:44

from django.db import migrations, models
import products.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('slug', models.SlugField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.PositiveIntegerField(db_index=True, default=0)),
                ('taxable', models.BooleanField(default=True, help_text='is this product taxable')),
                ('catalog', models.FileField(upload_to='', validators=[products.validators.validate_file_extension])),
                ('technical_features', models.TextField()),
                ('usable_for_organization_product', models.ManyToManyField(to='products.OrganizationProduct')),
            ],
        ),
    ]
